version: "3.7"


services:
  sonar:
    ## By default you can login as admin with password admin,
    image: sonarqube:7.9.2-community
    container_name: sonar
    hostname: sonar
    ports:
      - 90:9000
    volumes:
      # See https://hub.docker.com/_/sonarqube
      - sonarqube_conf:/opt/sonarqube/conf:rw
      - sonarqube_extensions:/opt/sonarqube/extensions:rw
      - sonarqube_downloads:/opt/sonarqube/extensions/downloads:rw
      - sonarqube_logs:/opt/sonarqube/logs:rw
      - sonarqube_data:/opt/sonarqube/data:rw
    #    environment:
    ##See:- https://hub.docker.com/_/sonarqube
#      - sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube
#      - sonar.jdbc.username=sonar
#      - sonar.jdbc.password=sonar

volumes:
  sonarqube_conf:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/data/conf
      o: bind
  sonarqube_extensions:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/data/extensions
      o: bind
  sonarqube_downloads:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/data/extensions/downloads
      o: bind
  sonarqube_logs:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/data/logs
      o: bind
  sonarqube_data:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/data/data
      o: bind
