version: '3.7'
## Refer:- https://github.com/jfrog/artifactory-docker-examples/tree/master/docker-compose/artifactory

## Learn how to setup named volume in docker-compose from:-
#  http://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/
volumes:
  artifactory_data:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/${JFROG_ARTIFACTORY_WORKSPACE}/artifactory_data
      o: bind
  postgresql_data:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/${JFROG_ARTIFACTORY_WORKSPACE}/postgresql_data
      o: bind
services:
  postgresql:
    image: docker.bintray.io/postgres:9.6.11
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=artifactory
      # The following must match the DB_USER and DB_PASSWORD values passed to Artifactory
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.17.0
    container_name: artifactory
    ports:
      - 80:8081
    depends_on:
      - postgresql
    links:
      - postgresql
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
    environment:
      - DB_TYPE=postgresql
      # The following must match the POSTGRES_USER and POSTGRES_PASSWORD values passed to PostgreSQL
      - DB_USER=artifactory
      - DB_PASSWORD=password
      # Add extra Java options by uncommenting the following line
      #- EXTRA_JAVA_OPTIONS=-Xms512m -Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000