#Create A Demo Pod
# kubectl create -f pod.yaml
#kubectl get pod demo
#kubectl logs --tail=3 demo
#kubectl delete pod demo

apiVersion: v1
kind: Pod
metadata:
  name: pv-recycler
  namespace: default
spec:
  restartPolicy: Never
  volumes:
    - name: vol
      hostPath:
        path: /any/path/it/will/be/replaced
  containers:
    - name: pv-recycler
      image: "k8s.gcr.io/busybox"
      command: ["/bin/sh", "-c", "test -e /scrub && rm -rf /scrub/..?* /scrub/.[!.]* /scrub/*  && test -z \"$(ls -A /scrub)\" || exit 1"]
      volumeMounts:
        - name: vol
          mountPath: /scrub