version: "3.7"

volumes:
  ## Learn how to setup named volume in docker-compose from:-
  #  http://blog.code4hire.com/2018/06/define-named-volume-with-host-mount-in-the-docker-compose-file/
  jenkins_workspace:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/jenkins-setup/custom-image/data
      o: bind
  artifactory_data:
    driver: local
    driver_opts:
      device: $PWD/jfrog-artifactory-setup/data/artifactory_data
      o: bind
      type: none
  postgresql_data:
    driver: local
    driver_opts:
      device: $PWD/jfrog-artifactory-setup/data/postgresql_data
      o: bind
      type: none
  ######## SONARQUBE VOLUMES --STARTS-- ########
  sonarqube_conf:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/sonar-setup/data/conf
      o: bind
  sonarqube_extensions:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/sonar-setup/data/extensions
      o: bind
  sonarqube_downloads:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/sonar-setup/data/extensions/downloads
      o: bind
  sonarqube_logs:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/sonar-setup/data/logs
      o: bind
  sonarqube_data:
    driver: local
    driver_opts:
      type: none
      #Note:- the use of $PWD which evaluates to present working directory and need not to define in .env file.
      #However jenkins_workspace needs to be defined in .env files
      device: $PWD/sonar-setup/data/data
      o: bind
  ######## SONARQUBE VOLUMES --ENDS-- ########

services:
  jenkins:
    build:
      context: $PWD/jenkins-setup/custom-image